### ISSUE TITLE
`StatBankClient.clientinfo` requires DataFrame.append, which is deprecated

### ISSUE THREAD

**Issue by pdtd** [gmohandas/denstatbank#10]
Hello, encountered `AttributeError: 'DataFrame' object has no attribute 'append'` upon calling `StatBankClient.clientinfo` when an existing [install of pandas is > 1.4.0](https://pandas.pydata.org/pandas-docs/version/1.4/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append).

Minimal example follows:
```python
from denstatbank import StatBankClient
c = StatBankClient("en")
c.tableinfo('folk1a', variables_df=True)
```
results in
```
Traceback (most recent call last):
  File "<example_dir>/ex.py", line 3, in <module>
    c.tableinfo('folk1a', variables_df=True)
  File "<venv_site-packages>/denstatbank/denstatbank.py", line 192, in tableinfo
    var_df = var_df.append(df)
             ^^^^^^^^^^^^^
  File "<venv_site-packages>/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
```

PR follows shortly.

**Comment by gmohandas** [comment]
thank you! merged your fix.
